// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Breadcrumb {
    /**
     * Creates a new Breadcrumb instance.
     * @param {Partial<Breadcrumb>} [$$source = {}] - The source object to create the Breadcrumb.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Breadcrumb instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Breadcrumb}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Breadcrumb(/** @type {Partial<Breadcrumb>} */($$parsedSource));
    }
}

export class DirectoryView {
    /**
     * Creates a new DirectoryView instance.
     * @param {Partial<DirectoryView>} [$$source = {}] - The source object to create the DirectoryView.
     */
    constructor($$source = {}) {
        if (!("dirId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dirId"] = "";
        }
        if (!("parentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parentId"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {Breadcrumb[]}
             */
            this["path"] = [];
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }
        if (!("offset" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["offset"] = 0;
        }
        if (!("limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["limit"] = 0;
        }
        if (!("hasMore" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasMore"] = false;
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {FileItem[]}
             */
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DirectoryView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DirectoryView}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        const $$createField8_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("path" in $$parsedSource) {
            $$parsedSource["path"] = $$createField3_0($$parsedSource["path"]);
        }
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField8_0($$parsedSource["items"]);
        }
        return new DirectoryView(/** @type {Partial<DirectoryView>} */($$parsedSource));
    }
}

export class FileItem {
    /**
     * Creates a new FileItem instance.
     * @param {Partial<FileItem>} [$$source = {}] - The source object to create the FileItem.
     */
    constructor($$source = {}) {
        if (!("fileId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileId"] = "";
        }
        if (!("parentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parentId"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("pickCode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pickCode"] = "";
        }
        if (!("isDirectory" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDirectory"] = false;
        }
        if (!("isVideo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isVideo"] = false;
        }
        if (!("isHiddenFile" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isHiddenFile"] = false;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["durationSec"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["resumeMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["subtitlePath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastPlayedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileItem(/** @type {Partial<FileItem>} */($$parsedSource));
    }
}

export class HiddenModeStatusView {
    /**
     * Creates a new HiddenModeStatusView instance.
     * @param {Partial<HiddenModeStatusView>} [$$source = {}] - The source object to create the HiddenModeStatusView.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["rememberedPassword"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HiddenModeStatusView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HiddenModeStatusView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HiddenModeStatusView(/** @type {Partial<HiddenModeStatusView>} */($$parsedSource));
    }
}

export class LoginSessionView {
    /**
     * Creates a new LoginSessionView instance.
     * @param {Partial<LoginSessionView>} [$$source = {}] - The source object to create the LoginSessionView.
     */
    constructor($$source = {}) {
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("qrCodeDataUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["qrCodeDataUrl"] = "";
        }
        if (!("qrCodeContent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["qrCodeContent"] = "";
        }
        if (!("expiresIn" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expiresIn"] = 0;
        }
        if (!("createdUnixSec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdUnixSec"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoginSessionView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoginSessionView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoginSessionView(/** @type {Partial<LoginSessionView>} */($$parsedSource));
    }
}

export class LoginStatusView {
    /**
     * Creates a new LoginStatusView instance.
     * @param {Partial<LoginStatusView>} [$$source = {}] - The source object to create the LoginStatusView.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("loggedIn" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["loggedIn"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {UserView | null | undefined}
             */
            this["user"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoginStatusView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoginStatusView}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField3_0($$parsedSource["user"]);
        }
        return new LoginStatusView(/** @type {Partial<LoginStatusView>} */($$parsedSource));
    }
}

export class OfflineListView {
    /**
     * Creates a new OfflineListView instance.
     * @param {Partial<OfflineListView>} [$$source = {}] - The source object to create the OfflineListView.
     */
    constructor($$source = {}) {
        if (!("quota" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["quota"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("activeCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["activeCount"] = 0;
        }
        if (!("failedCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failedCount"] = 0;
        }
        if (!("completedCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completedCount"] = 0;
        }
        if (!("tasks" in $$source)) {
            /**
             * @member
             * @type {OfflineTaskView[]}
             */
            this["tasks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OfflineListView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OfflineListView}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField5_0($$parsedSource["tasks"]);
        }
        return new OfflineListView(/** @type {Partial<OfflineListView>} */($$parsedSource));
    }
}

export class OfflineTaskView {
    /**
     * Creates a new OfflineTaskView instance.
     * @param {Partial<OfflineTaskView>} [$$source = {}] - The source object to create the OfflineTaskView.
     */
    constructor($$source = {}) {
        if (!("infoHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["infoHash"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("addTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["addTime"] = "";
        }
        if (!("updateTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updateTime"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("statusCode" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["statusCode"] = 0;
        }
        if (!("statusGroup" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["statusGroup"] = "";
        }
        if (!("percent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["percent"] = 0;
        }
        if (!("percentText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["percentText"] = "";
        }
        if (!("speedText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["speedText"] = "";
        }
        if (!("leftTimeText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["leftTimeText"] = "";
        }
        if (!("peers" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["peers"] = 0;
        }
        if (!("fileId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileId"] = "";
        }
        if (!("deleteFileId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deleteFileId"] = "";
        }
        if (!("dirId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dirId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OfflineTaskView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OfflineTaskView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OfflineTaskView(/** @type {Partial<OfflineTaskView>} */($$parsedSource));
    }
}

export class SearchResultView {
    /**
     * Creates a new SearchResultView instance.
     * @param {Partial<SearchResultView>} [$$source = {}] - The source object to create the SearchResultView.
     */
    constructor($$source = {}) {
        if (!("query" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["query"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }
        if (!("offset" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["offset"] = 0;
        }
        if (!("limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["limit"] = 0;
        }
        if (!("hasMore" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasMore"] = false;
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {FileItem[]}
             */
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResultView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResultView}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField5_0($$parsedSource["items"]);
        }
        return new SearchResultView(/** @type {Partial<SearchResultView>} */($$parsedSource));
    }
}

export class UserView {
    /**
     * Creates a new UserView instance.
     * @param {Partial<UserView>} [$$source = {}] - The source object to create the UserView.
     */
    constructor($$source = {}) {
        if (!("userId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["userId"] = 0;
        }
        if (!("userName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["userName"] = "";
        }
        if (!("faceUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["faceUrl"] = "";
        }
        if (!("isVip" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isVip"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["vipLabel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["vipForever"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["vipExpireAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["spaceTotal"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["spaceUsed"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["spaceRemain"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UserView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserView(/** @type {Partial<UserView>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Breadcrumb.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = FileItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = UserView.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = OfflineTaskView.createFrom;
const $$createType7 = $Create.Array($$createType6);
