// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pan$0 from "./internal/pan/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as player$0 from "./internal/player/models.js";

export class AddOfflineRequest {
    /**
     * Creates a new AddOfflineRequest instance.
     * @param {Partial<AddOfflineRequest>} [$$source = {}] - The source object to create the AddOfflineRequest.
     */
    constructor($$source = {}) {
        if (!("urls" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["urls"] = [];
        }
        if (!("saveDirId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["saveDirId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {pan$0.Breadcrumb[] | undefined}
             */
            this["saveDirPath"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AddOfflineRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AddOfflineRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("urls" in $$parsedSource) {
            $$parsedSource["urls"] = $$createField0_0($$parsedSource["urls"]);
        }
        if ("saveDirPath" in $$parsedSource) {
            $$parsedSource["saveDirPath"] = $$createField2_0($$parsedSource["saveDirPath"]);
        }
        return new AddOfflineRequest(/** @type {Partial<AddOfflineRequest>} */($$parsedSource));
    }
}

export class BootstrapResult {
    /**
     * Creates a new BootstrapResult instance.
     * @param {Partial<BootstrapResult>} [$$source = {}] - The source object to create the BootstrapResult.
     */
    constructor($$source = {}) {
        if (!("loggedIn" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["loggedIn"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {pan$0.UserView | null | undefined}
             */
            this["user"] = undefined;
        }
        if (!("hiddenMode" in $$source)) {
            /**
             * @member
             * @type {pan$0.HiddenModeStatusView}
             */
            this["hiddenMode"] = (new pan$0.HiddenModeStatusView());
        }
        if (!("hiddenModePasswordRemembered" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hiddenModePasswordRemembered"] = false;
        }
        if (!("settings" in $$source)) {
            /**
             * @member
             * @type {SettingsView}
             */
            this["settings"] = (new SettingsView());
        }
        if (!("currentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentId"] = "";
        }
        if (!("proxyBase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxyBase"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BootstrapResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BootstrapResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType5;
        const $$createField4_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField1_0($$parsedSource["user"]);
        }
        if ("hiddenMode" in $$parsedSource) {
            $$parsedSource["hiddenMode"] = $$createField2_0($$parsedSource["hiddenMode"]);
        }
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField4_0($$parsedSource["settings"]);
        }
        return new BootstrapResult(/** @type {Partial<BootstrapResult>} */($$parsedSource));
    }
}

export class DeleteOfflineRequest {
    /**
     * Creates a new DeleteOfflineRequest instance.
     * @param {Partial<DeleteOfflineRequest>} [$$source = {}] - The source object to create the DeleteOfflineRequest.
     */
    constructor($$source = {}) {
        if (!("hashes" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["hashes"] = [];
        }
        if (!("deleteFiles" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["deleteFiles"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteOfflineRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeleteOfflineRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hashes" in $$parsedSource) {
            $$parsedSource["hashes"] = $$createField0_0($$parsedSource["hashes"]);
        }
        return new DeleteOfflineRequest(/** @type {Partial<DeleteOfflineRequest>} */($$parsedSource));
    }
}

export class DirectoryTargetView {
    /**
     * Creates a new DirectoryTargetView instance.
     * @param {Partial<DirectoryTargetView>} [$$source = {}] - The source object to create the DirectoryTargetView.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {pan$0.Breadcrumb[]}
             */
            this["path"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DirectoryTargetView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DirectoryTargetView}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("path" in $$parsedSource) {
            $$parsedSource["path"] = $$createField1_0($$parsedSource["path"]);
        }
        return new DirectoryTargetView(/** @type {Partial<DirectoryTargetView>} */($$parsedSource));
    }
}

export class PlayRequest {
    /**
     * Creates a new PlayRequest instance.
     * @param {Partial<PlayRequest>} [$$source = {}] - The source object to create the PlayRequest.
     */
    constructor($$source = {}) {
        if (!("pickCode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pickCode"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("startMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startMs"] = 0;
        }
        if (!("fromStart" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["fromStart"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["subtitle"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["playerId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlayRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlayRequest(/** @type {Partial<PlayRequest>} */($$parsedSource));
    }
}

export class PlayResult {
    /**
     * Creates a new PlayResult instance.
     * @param {Partial<PlayResult>} [$$source = {}] - The source object to create the PlayResult.
     */
    constructor($$source = {}) {
        if (!("playerId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["playerId"] = "";
        }
        if (!("playerName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["playerName"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("startMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startMs"] = 0;
        }
        if (!("resumeUsed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["resumeUsed"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["subtitle"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlayResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlayResult(/** @type {Partial<PlayResult>} */($$parsedSource));
    }
}

export class PlaybackStateView {
    /**
     * Creates a new PlaybackStateView instance.
     * @param {Partial<PlaybackStateView>} [$$source = {}] - The source object to create the PlaybackStateView.
     */
    constructor($$source = {}) {
        if (!("pickCode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pickCode"] = "";
        }
        if (!("resumeMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["resumeMs"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["resumeText"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["subtitlePath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["subtitleName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastPlayedAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaybackStateView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlaybackStateView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaybackStateView(/** @type {Partial<PlaybackStateView>} */($$parsedSource));
    }
}

export class SettingsView {
    /**
     * Creates a new SettingsView instance.
     * @param {Partial<SettingsView>} [$$source = {}] - The source object to create the SettingsView.
     */
    constructor($$source = {}) {
        if (!("preferredPlayer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["preferredPlayer"] = "";
        }
        if (!("players" in $$source)) {
            /**
             * @member
             * @type {player$0.Status[]}
             */
            this["players"] = [];
        }
        if (!("configPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configPath"] = "";
        }
        if (!("showTitleBadges" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showTitleBadges"] = false;
        }
        if (!("cleanTitleDisplay" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cleanTitleDisplay"] = false;
        }
        if (!("uiScalePercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uiScalePercent"] = 0;
        }
        if (!("themeMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["themeMode"] = "";
        }
        if (!("themeColor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["themeColor"] = "";
        }
        if (!("smallFileFilterMB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["smallFileFilterMB"] = 0;
        }
        if (!("fileListDensity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileListDensity"] = "";
        }
        if (!("offlineRecentTargets" in $$source)) {
            /**
             * @member
             * @type {DirectoryTargetView[]}
             */
            this["offlineRecentTargets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsView}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType8;
        const $$createField10_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("players" in $$parsedSource) {
            $$parsedSource["players"] = $$createField1_0($$parsedSource["players"]);
        }
        if ("offlineRecentTargets" in $$parsedSource) {
            $$parsedSource["offlineRecentTargets"] = $$createField10_0($$parsedSource["offlineRecentTargets"]);
        }
        return new SettingsView(/** @type {Partial<SettingsView>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = pan$0.Breadcrumb.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = pan$0.UserView.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = pan$0.HiddenModeStatusView.createFrom;
const $$createType6 = SettingsView.createFrom;
const $$createType7 = player$0.Status.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = DirectoryTargetView.createFrom;
const $$createType10 = $Create.Array($$createType9);
