// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as library$0 from "./internal/library/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pan$0 from "./internal/pan/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.AddOfflineRequest} req
 * @returns {$CancellablePromise<pan$0.OfflineListView | null>}
 */
export function AddOfflineTasks(req) {
    return $Call.ByID(12168331, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.BootstrapResult | null>}
 */
export function Bootstrap() {
    return $Call.ByID(1258932017).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<pan$0.LoginStatusView | null>}
 */
export function CheckQRCodeLogin(sessionID) {
    return $Call.ByID(3383797098, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} pickCode
 * @returns {$CancellablePromise<$models.PlaybackStateView | null>}
 */
export function ClearPlaybackProgress(pickCode) {
    return $Call.ByID(2592270624, pickCode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} pickCode
 * @returns {$CancellablePromise<$models.PlaybackStateView | null>}
 */
export function ClearSubtitlePath(pickCode) {
    return $Call.ByID(200284885, pickCode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {$models.DeleteOfflineRequest} req
 * @returns {$CancellablePromise<pan$0.OfflineListView | null>}
 */
export function DeleteOfflineTasks(req) {
    return $Call.ByID(4180208773, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} playerID
 * @returns {$CancellablePromise<$models.SettingsView | null>}
 */
export function DeletePlayerPath(playerID) {
    return $Call.ByID(3854673356, playerID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} titleID
 * @returns {$CancellablePromise<$models.LibraryTitleDetailView | null>}
 */
export function GetLibraryDetail(titleID) {
    return $Call.ByID(869615043, titleID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.LibrarySnapshotView | null>}
 */
export function GetLibrarySnapshot() {
    return $Call.ByID(3940551486).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ScrapeJobStatusView | null>}
 */
export function GetScraperStatus() {
    return $Call.ByID(3207301845).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @param {string} dirID
 * @param {number} offset
 * @param {number} limit
 * @returns {$CancellablePromise<pan$0.DirectoryView | null>}
 */
export function ListDirectory(dirID, offset, limit) {
    return $Call.ByID(3882022436, dirID, offset, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @returns {$CancellablePromise<pan$0.OfflineListView | null>}
 */
export function ListOfflineTasks() {
    return $Call.ByID(2215408854).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} cookie
 * @returns {$CancellablePromise<pan$0.LoginStatusView | null>}
 */
export function LoginWithCookie(cookie) {
    return $Call.ByID(3671735420, cookie).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Logout() {
    return $Call.ByID(1110373539);
}

/**
 * @returns {$CancellablePromise<$models.ScrapeJobStatusView | null>}
 */
export function PauseScraper() {
    return $Call.ByID(1130369861).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @param {$models.PlayRequest} req
 * @returns {$CancellablePromise<$models.PlayResult | null>}
 */
export function PlayFile(req) {
    return $Call.ByID(4039908549, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * @param {$models.PlayRequest} req
 * @returns {$CancellablePromise<$models.BuiltinPlaybackSource | null>}
 */
export function PrepareBuiltinPlayback(req) {
    return $Call.ByID(3852339662, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * @param {string} dirID
 * @returns {$CancellablePromise<pan$0.DirectoryView | null>}
 */
export function PreviewDirectory(dirID) {
    return $Call.ByID(317703958, dirID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @param {$models.LibraryPlayRequest} req
 * @returns {$CancellablePromise<$models.PlayRequest | null>}
 */
export function ResolveLibraryPlayRequest(req) {
    return $Call.ByID(2178307905, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function RevealConfigPath() {
    return $Call.ByID(3976172685);
}

/**
 * @param {string} value
 * @returns {$CancellablePromise<$models.SettingsView | null>}
 */
export function SaveFileListDensity(value) {
    return $Call.ByID(2930785366, value).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<$models.SettingsView | null>}
 */
export function SaveHideSmallFilesEnabled(enabled) {
    return $Call.ByID(609920859, enabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} pickCode
 * @param {string} name
 * @param {number} positionMS
 * @returns {$CancellablePromise<$models.PlaybackStateView | null>}
 */
export function SavePlaybackProgress(pickCode, name, positionMS) {
    return $Call.ByID(3783574330, pickCode, name, positionMS).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} playerID
 * @param {boolean} disabled
 * @returns {$CancellablePromise<$models.SettingsView | null>}
 */
export function SavePlayerDisabled(playerID, disabled) {
    return $Call.ByID(1293434149, playerID, disabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} playerID
 * @param {string} path
 * @returns {$CancellablePromise<$models.SettingsView | null>}
 */
export function SavePlayerPath(playerID, path) {
    return $Call.ByID(597575766, playerID, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} playerID
 * @returns {$CancellablePromise<$models.SettingsView | null>}
 */
export function SavePreferredPlayer(playerID) {
    return $Call.ByID(2447528288, playerID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {$models.DirectoryTargetView[]} targets
 * @returns {$CancellablePromise<$models.SettingsView | null>}
 */
export function SaveScraperDirectories(targets) {
    return $Call.ByID(3629405465, targets).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string[]} sources
 * @param {string} language
 * @param {boolean} autoScan
 * @param {boolean} overwrite
 * @param {boolean} downloadImages
 * @param {string} tmdbReadAccessToken
 * @returns {$CancellablePromise<$models.SettingsView | null>}
 */
export function SaveScraperSettings(sources, language, autoScan, overwrite, downloadImages, tmdbReadAccessToken) {
    return $Call.ByID(3159247787, sources, language, autoScan, overwrite, downloadImages, tmdbReadAccessToken).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<$models.SettingsView | null>}
 */
export function SaveShowTitleBadgesEnabled(enabled) {
    return $Call.ByID(1212603770, enabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {number} value
 * @returns {$CancellablePromise<$models.SettingsView | null>}
 */
export function SaveSmallFileFilterMB(value) {
    return $Call.ByID(3067566256, value).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} keyword
 * @param {number} offset
 * @param {number} limit
 * @returns {$CancellablePromise<pan$0.SearchResultView | null>}
 */
export function SearchFiles(keyword, offset, limit) {
    return $Call.ByID(3203090108, keyword, offset, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * @param {string} playerID
 * @returns {$CancellablePromise<$models.SettingsView | null>}
 */
export function SelectPlayerPath(playerID) {
    return $Call.ByID(1255019015, playerID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} pickCode
 * @returns {$CancellablePromise<$models.PlaybackStateView | null>}
 */
export function SelectSubtitlePath(pickCode) {
    return $Call.ByID(2545156290, pickCode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectTorrentFileAsMagnet() {
    return $Call.ByID(2174593417);
}

/**
 * @returns {$CancellablePromise<pan$0.LoginSessionView | null>}
 */
export function StartQRCodeLogin() {
    return $Call.ByID(2084241698).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ScrapeJobStatusView | null>}
 */
export function StartScraper() {
    return $Call.ByID(2080015387).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

// Private type creation functions
const $$createType0 = pan$0.OfflineListView.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.BootstrapResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = pan$0.LoginStatusView.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.PlaybackStateView.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.SettingsView.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = library$0.TitleDetail.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = library$0.LibrarySnapshot.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = library$0.ScrapeJobStatus.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = pan$0.DirectoryView.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = $models.PlayResult.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = $models.BuiltinPlaybackSource.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = $models.PlayRequest.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = pan$0.SearchResultView.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = pan$0.LoginSessionView.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
