// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {pan} from '../models';

export function AddOfflineTasks(arg1:main.AddOfflineRequest):Promise<pan.OfflineListView>;

export function Bootstrap():Promise<main.BootstrapResult>;

export function CheckQRCodeLogin(arg1:string):Promise<pan.LoginStatusView>;

export function ClearPlaybackProgress(arg1:string):Promise<main.PlaybackStateView>;

export function ClearSubtitlePath(arg1:string):Promise<main.PlaybackStateView>;

export function DeleteOfflineTasks(arg1:main.DeleteOfflineRequest):Promise<pan.OfflineListView>;

export function DeletePlayerPath(arg1:string):Promise<main.SettingsView>;

export function ListDirectory(arg1:string,arg2:number,arg3:number):Promise<pan.DirectoryView>;

export function ListOfflineTasks():Promise<pan.OfflineListView>;

export function LoginWithCookie(arg1:string):Promise<pan.LoginStatusView>;

export function Logout():Promise<void>;

export function NotifyError(arg1:string,arg2:Error):Promise<void>;

export function PlayFile(arg1:main.PlayRequest):Promise<main.PlayResult>;

export function PreviewDirectory(arg1:string):Promise<pan.DirectoryView>;

export function RevealConfigPath():Promise<string>;

export function SaveFileListDensity(arg1:string):Promise<main.SettingsView>;

export function SaveHideSmallFilesEnabled(arg1:boolean):Promise<main.SettingsView>;

export function SavePlayerDisabled(arg1:string,arg2:boolean):Promise<main.SettingsView>;

export function SavePlayerPath(arg1:string,arg2:string):Promise<main.SettingsView>;

export function SavePreferredPlayer(arg1:string):Promise<main.SettingsView>;

export function SaveShowTitleBadgesEnabled(arg1:boolean):Promise<main.SettingsView>;

export function SaveSmallFileFilterMB(arg1:number):Promise<main.SettingsView>;

export function SearchFiles(arg1:string,arg2:number,arg3:number):Promise<pan.SearchResultView>;

export function SelectPlayerPath(arg1:string):Promise<main.SettingsView>;

export function SelectSubtitlePath(arg1:string):Promise<main.PlaybackStateView>;

export function SelectTorrentFileAsMagnet():Promise<string>;

export function StartQRCodeLogin():Promise<pan.LoginSessionView>;
