// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddOfflineTasks(arg1) {
  return window['go']['main']['App']['AddOfflineTasks'](arg1);
}

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CheckQRCodeLogin(arg1) {
  return window['go']['main']['App']['CheckQRCodeLogin'](arg1);
}

export function ClearPlaybackProgress(arg1) {
  return window['go']['main']['App']['ClearPlaybackProgress'](arg1);
}

export function ClearSubtitlePath(arg1) {
  return window['go']['main']['App']['ClearSubtitlePath'](arg1);
}

export function DeletePlayerPath(arg1) {
  return window['go']['main']['App']['DeletePlayerPath'](arg1);
}

export function DeleteOfflineTasks(arg1) {
  return window['go']['main']['App']['DeleteOfflineTasks'](arg1);
}

export function ListDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListDirectory'](arg1, arg2, arg3);
}

export function ListOfflineTasks() {
  return window['go']['main']['App']['ListOfflineTasks']();
}

export function LoginWithCookie(arg1) {
  return window['go']['main']['App']['LoginWithCookie'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function NotifyError(arg1, arg2) {
  return window['go']['main']['App']['NotifyError'](arg1, arg2);
}

export function PlayFile(arg1) {
  return window['go']['main']['App']['PlayFile'](arg1);
}

export function PreviewDirectory(arg1) {
  return window['go']['main']['App']['PreviewDirectory'](arg1);
}

export function RevealConfigPath() {
  return window['go']['main']['App']['RevealConfigPath']();
}

export function SearchFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchFiles'](arg1, arg2, arg3);
}

export function SaveShowTitleBadgesEnabled(arg1) {
  return window['go']['main']['App']['SaveShowTitleBadgesEnabled'](arg1);
}

export function SaveFileListDensity(arg1) {
  return window['go']['main']['App']['SaveFileListDensity'](arg1);
}

export function SaveSmallFileFilterMB(arg1) {
  return window['go']['main']['App']['SaveSmallFileFilterMB'](arg1);
}

export function SavePlayerPath(arg1, arg2) {
  return window['go']['main']['App']['SavePlayerPath'](arg1, arg2);
}

export function SavePreferredPlayer(arg1) {
  return window['go']['main']['App']['SavePreferredPlayer'](arg1);
}

export function SavePlayerDisabled(arg1, arg2) {
  return window['go']['main']['App']['SavePlayerDisabled'](arg1, arg2);
}

export function SelectPlayerPath(arg1) {
  return window['go']['main']['App']['SelectPlayerPath'](arg1);
}

export function SelectSubtitlePath(arg1) {
  return window['go']['main']['App']['SelectSubtitlePath'](arg1);
}

export function SelectTorrentFileAsMagnet() {
  return window['go']['main']['App']['SelectTorrentFileAsMagnet']();
}

export function StartQRCodeLogin() {
  return window['go']['main']['App']['StartQRCodeLogin']();
}
